require: rubocop-sketchup

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'tests/**/*'
  SketchUp:
    TargetSketchUpVersion: 2015

# SketchUp API uses camel case method names for observers and tool interfaces.
Naming/MethodName:
  Enabled: false

# Let Git client handle file endings.
Layout/EndOfLine:
  Enabled: false

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes

SketchupDeprecations:
  Enabled: true

SketchupPerformance:
  Enabled: true

# This is not an extension, just a single module.
SketchupRequirements:
  Enabled: false

SketchupSuggestions:
  Enabled: true
